// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXgth5Koqdgm-OurYFGZC61Rm0Eh3a3JI',
    appId: '1:682811183088:web:0ae7d69b85789ebf6bd735',
    messagingSenderId: '682811183088',
    projectId: 'trqabmobile',
    authDomain: 'trqabmobile.firebaseapp.com',
    storageBucket: 'trqabmobile.appspot.com',
    measurementId: 'G-HSBNV6WGHE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbl2jbRKkuMmbwJmyA5ike9hLHMql0ieg',
    appId: '1:682811183088:android:39fc462b0a2085906bd735',
    messagingSenderId: '682811183088',
    projectId: 'trqabmobile',
    storageBucket: 'trqabmobile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3lN2w7oLAyMvXsO0NlxhmSmhi7v9fC7A',
    appId: '1:682811183088:ios:6ec74638eb24eca36bd735',
    messagingSenderId: '682811183088',
    projectId: 'trqabmobile',
    storageBucket: 'trqabmobile.appspot.com',
    iosBundleId: 'com.example.petShop',
  );
}
